//import tooltips from './tooltips';
import photogalleries from './photogalleries';
import ScrollReveal from 'scrollreveal';

function libraries($) {

	/*
		Tooltips
		 - Add's tool tips to specific class elements to help describe what they are doing.
	*/
	//tooltips();

	/*
		Photoswipe Galleries
		 - Enhances Image sections by allowing Gallery's to be generated by their groups.
	*/
	photogalleries();	

	/*
		Scroll Reveal Elements 
	*/
	ScrollReveal().reveal('.reveal');

}

export default libraries;